# Generated by Django 4.0.3 on 2022-04-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('dob', models.DateField(default=0, null=True)),
                ('locality_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DiagExtended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diag_id', models.PositiveIntegerField()),
                ('rating', models.FloatField()),
                ('opening', models.TimeField()),
                ('closing', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('dob', models.DateField(default=0, null=True)),
                ('email_id', models.EmailField(default=0, max_length=254, null=True)),
                ('manager', models.CharField(default=0, max_length=50, null=True)),
                ('locality_id', models.PositiveIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagonosticFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diag_id', models.PositiveIntegerField()),
                ('patient_id', models.PositiveBigIntegerField()),
                ('rating', models.FloatField()),
                ('review', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('dob', models.DateField(default=0, null=True)),
                ('email_id', models.EmailField(default=0, max_length=254, null=True)),
                ('speciality', models.CharField(max_length=25)),
                ('hospital_id', models.PositiveIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorExtended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.PositiveIntegerField()),
                ('rating', models.FloatField()),
                ('languages_known', models.CharField(max_length=50)),
                ('year_of_experience', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.PositiveIntegerField()),
                ('patient_id', models.PositiveBigIntegerField()),
                ('rating', models.FloatField()),
                ('review', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=250)),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'doctor'), (2, 'pharmacy'), (3, 'diagonostic')])),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('locality_id', models.PositiveIntegerField(null=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('email_id', models.EmailField(default=0, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_code', models.CharField(max_length=8)),
                ('latitude', models.FloatField(default=0, null=True)),
                ('longitude', models.FloatField(default=0, null=True)),
                ('landmark', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('dob', models.DateField(default=0, null=True)),
                ('locality_id', models.IntegerField()),
                ('gender', models.PositiveIntegerField(choices=[(1, 'male'), (2, 'female')])),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.PositiveIntegerField()),
                ('date_time', models.DateTimeField()),
                ('purpose', models.PositiveSmallIntegerField(choices=[(1, 'doctor'), (2, 'medicines'), (3, 'diagonostic_test')])),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('discount', models.FloatField()),
                ('net_amount', models.FloatField()),
                ('payment_type', models.PositiveSmallIntegerField(choices=[(1, 'cash'), (2, 'debit_card'), (3, 'credit_card'), (4, 'upi')])),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('dob', models.DateField(default=0, null=True)),
                ('email_id', models.EmailField(default=0, max_length=254, null=True)),
                ('manager', models.CharField(default=0, max_length=50, null=True)),
                ('locality_id', models.PositiveIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyExtended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_id', models.PositiveIntegerField()),
                ('rating', models.FloatField()),
                ('opening', models.TimeField()),
                ('closing', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharma_id', models.PositiveIntegerField()),
                ('patient_id', models.PositiveBigIntegerField()),
                ('rating', models.FloatField()),
                ('review', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diag_id', models.PositiveIntegerField()),
                ('test_name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
    ]
